spring.application.name=youtubebuddy


# ==========================
# Default AI Model
# ==========================
ai.default.model=llama-3.3-70b-versatile

# ==========================
# Gemini
# ==========================
#
gemini.api.key=${GEMINI_API_KEY}

# ==========================
# Groq
# ==========================
#
groq.api.key=${GROQ_API_KEY}

# ==========================
# Ollama
# ==========================
ollama.base.url=http://localhost:11434